### ISSUE TITLE
cannot reserve inbound connection: resource limit exceeded

### ISSUE THREAD

**Issue by mindstyle85** [celestiaorg/celestia-node#1527]
### Celestia Node version

0.6.1

### OS

ubuntu 20.04

### Steps to reproduce it

running the bridge locally, connected to our validator, so using localhost to init and start it

### Expected result

wroking normally (though it does sync new heads)

### Actual result

lots of these in the logs:

Dec 22 09:15:38 val02-tia-t celestia[906823]: 2022-12-22T09:15:38.062Z        WARN        net/identify        identify/id.go:330        failed to identify 12D3KooWFEveDPBas59EkMDsHFvNaC3ZtYsAZ95QzRCr2K2SEhFU: Application error 0x0: conn-752705: system: cannot reserve inbound connection: resource limit exceeded

**Comment by Wondertan** [comment]
@mindstyle85, this is fixed in 0.6.2

**Comment by jevonearth** [comment]
I tested this today with the v0.6.2-rc1 tag and it appears to still be an issue.


My build details;
```
➜  celestia-node git:(0ab5df6) celestia version
Semantic version: v0.6.2-rc1
Commit: 0ab5df64adb7a1452043ef7677a448ec1b103dfb
Build Date: Wed Jan 11 08:51:12 AM PST 2023
System version: amd64/linux
Golang version: go1.19.4
```

The log line in question;
```
2023-01-11T08:51:57.554-0800    WARN    net/identify    identify/id.go:330      failed to identify 12D3KooWHdYWiwCPuZvas3J7fRWoP7vPuDjAXQ42yTtKeTXchYMw: Application error 0x0: conn-3947267: system: cannot reserve inbound connection: resource limit exceeded
```

**Comment by jevonearth** [comment]
I decided to test on today's main, too (commit 97c07a44c5966af738c138e29be6e4a65c2db481) and the log line is still present on that build, but, non-empirically, it seems to occur at a lower rate FWIW.

```
2023-01-11T09:17:03.204-0800    WARN    net/identify    identify/id.go:334      failed to identify 12D3KooWQRTbRipEfcZ4L2H7Gc44dsZAkL89zC4xbpYXEc4CwQvQ: Application error 0x0 (remote): conn-3580066: system: cannot reserve inbound connection: resource limit exceeded
```


Version details;

```
➜  ~ celestia version
Semantic version: v0.6.2-rc1-26-g97c07a4
Commit: 97c07a44c5966af738c138e29be6e4a65c2db481
Build Date: Wed Jan 11 08:57:16 AM PST 2023
System version: amd64/linux
Golang version: go1.19.4
```
