### ISSUE TITLE
blob.GetAll fails from a certain height

### ISSUE THREAD

**Issue by christopherbrumm** [celestiaorg/celestia-node#3185]
### Celestia Node version

Semantic version: v0.12.4 Commit: 8e5a71746bc9bd9300ad3e4853797e64fdd1d018 Build Date: Fri Feb  9 11:20:30 UTC 2024 Golang version: go1.21.1

### OS

System version: amd64/linux

### Install tools

Followed step-by-step tutorial in the docs to install a celestia DA full node for Mainnet Beta
- https://docs.celestia.org/nodes/celestia-node
- https://docs.celestia.org/nodes/full-storage-nod

### Others

Running on AWS `m5.4xlarge`: 
- 16 vCPU
- 64GB RAM

### Steps to reproduce it

- Setup celestia DA full node
- Start syncing process
- Write a script to query `blob.GetAll` for each height, e.g. using
`curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $CELESTIA_NODE_AUTH_TOKEN" -d '{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "blob.GetAll",
    "params": [
        $HEIGHT,
        ["AAAAAAAAAAAAAAAAAAAAAAAAAIZiad33fbxA7Z0="]
    ]
}' 127.0.0.1:26658`

### Expected result

I expect to get a response for every request to store all blobs for a given namespace.

### Actual result

Instead, the request stalls starting from a certain height (observed starting from height`740731`, `740740`), although requesting all blobs for a lower height works totally fine. The node doesn't throw errors when requesting, CPU and RAM usage limits are not exceeded. A node restart ends in the same issue, although resetting the store with `celestia full unsafe-reset-store`.

### Relevant log output

```Shell
Couldn't find any possibly related node logs
```

**Comment by vgonkivs** [comment]
Might be related to https://github.com/celestiaorg/celestia-node/issues/2915

**Comment by walldiss** [comment]
Could you please run your node with metrics flags pointing to our otel collecter? We would also need your peerID (show at node start) to filter out your node metrics.
```
--metrics.endpoint otel.celestia.observer

```

**Comment by renaynay** [comment]
>Today I found out that restarting the node or the whole server fixes the issue shortly, but just increases that certain height: I couldn't query blob.GetAll on my instance for all heights >= 740740; after restarting, I can't query it for all heights >= 740817.

Seems related to https://github.com/celestiaorg/go-header/pull/159

**Comment by christopherbrumm** [comment]
I have reproduced the issue and I can confirm your thesis @vgonkivs, because the error occurs when querying one blob more than one time. However, I've appended the logs of my node when reproducing:

[celestia-node.txt](https://github.com/celestiaorg/celestia-node/files/14435882/celestia-node.txt)

In another terminal, I have executed the following commands (every time I exited the curl execution with `^C`, the response was stalling for more than 30s):
`**Wed Feb 28 14:51:51 UTC 2024**

ubuntu@ip-172-31-1-21:~$ curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $CELESTIA_NODE_AUTH_TOKEN" -d '{ "id": 1, "jsonrpc": "2.0", "method": "blob.GetAll", "params": [ 745000, ["AAAAAAAAAAAAAAAAAAAAAAAAAIZiad33fbxA7Z0="] ] }' 127.0.0.1:26658
{"jsonrpc":"2.0","id":1,"error":{"code":1,"message":"getting blobs for namespace(00000000000000000000000000000000000000866269ddf77dbc40ed9d): blob: not found\nblob: not found"}}

ubuntu@ip-172-31-1-21:~$ curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $CELESTIA_NODE_AUTH_TOKEN" -d '{ "id": 1, "jsonrpc": "2.0", "method": "blob.GetAll", "params": [ 745000, ["AAAAAAAAAAAAAAAAAAAAAAAAAIZiad33fbxA7Z0="] ] }' 127.0.0.1:26658
**^C**

ubuntu@ip-172-31-1-21:~$ curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $CELESTIA_NODE_AUTH_TOKEN" -d '{ "id": 1, "jsonrpc": "2.0", "method": "blob.GetAll", "params": [ 745010, ["AAAAAAAAAAAAAAAAAAAAAAAAAIZiad33fbxA7Z0="] ] }' 127.0.0.1:26658
{"jsonrpc":"2.0","id":1,"error":{"code":1,"message":"getting blobs for namespace(00000000000000000000000000000000000000866269ddf77dbc40ed9d): blob: not found\nblob: not found"}}

ubuntu@ip-172-31-1-21:~$ curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $CELESTIA_NODE_AUTH_TOKEN" -d '{ "id": 1, "jsonrpc": "2.0", "method": "blob.GetAll", "params": [ 745010, ["AAAAAAAAAAAAAAAAAAAAAAAAAIZiad33fbxA7Z0="] ] }' 127.0.0.1:26658
{"jsonrpc":"2.0","id":1,"error":{"code":1,"message":"getting blobs for namespace(00000000000000000000000000000000000000866269ddf77dbc40ed9d): blob: not found\nblob: not found"}}

ubuntu@ip-172-31-1-21:~$ curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $CELESTIA_NODE_AUTH_TOKEN" -d '{ "id": 1, "jsonrpc": "2.0", "method": "blob.GetAll", "params": [ 745010, ["AAAAAAAAAAAAAAAAAAAAAAAAAIZiad33fbxA7Z0="] ] }' 127.0.0.1:26658
{"jsonrpc":"2.0","id":1,"error":{"code":1,"message":"getting blobs for namespace(00000000000000000000000000000000000000866269ddf77dbc40ed9d): blob: not found\nblob: not found"}}

ubuntu@ip-172-31-1-21:~$ curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $CELESTIA_NODE_AUTH_TOKEN" -d '{ "id": 1, "jsonrpc": "2.0", "method": "blob.GetAll", "params": [ 745010, ["AAAAAAAAAAAAAAAAAAAAAAAAAIZiad33fbxA7Z0="] ] }' 127.0.0.1:26658
**^C**`

**Comment by Wondertan** [comment]
@christopherbrumm, could you also test this behavior on the LN? I can see you using FN and we wonder if that's consistent across node types, particularly light

**Comment by christopherbrumm** [comment]
> @christopherbrumm, could you also test this behavior on the LN? I can see you using FN and we wonder if that's consistent across node types, particularly light

I was able to reproduce the issue on the LN. Will provide docs if required.

**Comment by christopherbrumm** [comment]
For completeness, linking the script to reproduce the issue in this thread:

https://github.com/christopherbrumm/scripts/tree/main/celestia

**Comment by vgonkivs** [comment]
Hello, @christopherbrumm. Thanks for the script. It helped a lot. Yesterday I had a chance to reproduce this issue. It seems that @renaynay was right: the root cause was in syncer. This issue was fixed at https://github.com/celestiaorg/go-header/pull/159. I tried your script on version v0.13(which already contains the fix) and for now, it works fine. Could you please also try v0.13?

**Comment by christopherbrumm** [comment]
That's great news, will try and confirm it asap in order to close this issue.

Thanks a lot!

**Comment by christopherbrumm** [comment]
Hi @vgonkivs, after five attempts with different setups, I can confirm that the upgrade to v0.13 did not completely fix the reported issue.

The node still stalls at a certain height and makes blob requests not possible. I am still using the provided script to replicate this issue.

Also, I've noticed another issue that occurs when requesting share.GetEDS. Essentially, it mirrors the blob issue: the node stalls when requesting data above a certain level. I have added an additional script to reproduce this issue with more context in the [README](https://github.com/christopherbrumm/scripts/tree/main/celestia).

I deployed five nodes on five different instances. While four of them have the issues listed, one is working fine. After realizing that one node has no problems providing blobs and shares, I tried to duplicate the setup. However, a node with identical setup shows the same problems again.

cc @Wondertan

**Comment by christopherbrumm** [comment]
Currently running 3 nodes on a fresh server and for all 3 the scripts are running through super smoothly. 

Will keep this thread updated.

**Comment by vgonkivs** [comment]
I guess we can close this issue then. Regarding the high duration of some requests: the current protocol for getting shares is slow(a known problem) and we are currently working on better solutions.

cc @Wondertan

**Comment by Wondertan** [comment]
Yes, lets close then
